version: '2'
services:
   db:
     image: postgres:9.5
     ports: 5432
   web:
     image: aws/web:v0
     environment:
       - DJANGO_SETTINGS_MODULE=app.setting_postgres
     command: python3 manage.py runserver 0.0.0.0:8000
     ports:
       - "80:8000"
     depends_on:
       - db
   sentiment:
     image: aws/sentiment:v0
     environment:
       - DJANGO_SETTINGS_MODULE=robo_app.prod_settings
     depends_on:
       - db
